let q1 = document.querySelector("#q1")
let a1 = document.querySelector("#a1")
let q2 = document.querySelector("#q2")
let a2 = document.querySelector("#a2")
let q3 = document.querySelector("#q3")
let a3 = document.querySelector("#a3")
let q4 = document.querySelector("#q4")
let a4 = document.querySelector("#a4")
let q5 = document.querySelector("#q5")
let a5 = document.querySelector("#a5")

q1.addEventListener("click", () => {
    a1.classList.remove("hidden-answers")
    a1.classList.add("answers")
    a2.classList.add("hidden-answers")
    a3.classList.add("hidden-answers")
    a4.classList.add("hidden-answers")
    a5.classList.add("hidden-answers")
})
q2.addEventListener("click", () => {
    a2.classList.remove("hidden-answers")
    a2.classList.add("answers")
    a1.classList.add("hidden-answers")
    a3.classList.add("hidden-answers")
    a4.classList.add("hidden-answers")
    a5.classList.add("hidden-answers")
})
q3.addEventListener("click", () => {
    a3.classList.remove("hidden-answers")
    a3.classList.add("answers")
    a2.classList.add("hidden-answers")
    a1.classList.add("hidden-answers")
    a4.classList.add("hidden-answers")
    a5.classList.add("hidden-answers")
})
q4.addEventListener("click", () => {
    a4.classList.remove("hidden-answers")
    a4.classList.add("answers")
    a2.classList.add("hidden-answers")
    a3.classList.add("hidden-answers")
    a1.classList.add("hidden-answers")
    a5.classList.add("hidden-answers")
})
q5.addEventListener("click", () => {
    a5.classList.remove("hidden-answers")
    a5.classList.add("answers")
    a2.classList.add("hidden-answers")
    a3.classList.add("hidden-answers")
    a4.classList.add("hidden-answers")
    a1.classList.add("hidden-answers")
})